# Generated by Django 3.0.6 on 2020-05-24 18:59

import apps.commons.utils.helpers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255, unique=True)),
                ('scheduled_for', models.DateTimeField(null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.commons.utils.helpers.get_upload_path)),
                ('body', models.TextField(null=True)),
                ('deadline', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Denied', 'Denied'), ('Published', 'Published'), ('Scheduled', 'Scheduled'), ('Expired', 'Expired'), ('Deleted', 'Deleted')], db_index=True, default='Published', max_length=50)),
                ('privacy', models.CharField(choices=[('Only me', 'Only me'), ('Public', 'Public'), ('Followers', 'Followers')], default='Public', max_length=50)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='commons.Category')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_title_with_author'),
        ),
    ]
